spring:
  application:
    name: pagamento-service
  rabbitmq:
    host: rabbit
    port: 5672
server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka