spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  rabbitmq:
    host: rabbit
    port: 5672

springdoc:
  swagger-ui:
    config-url: /produto/v3/api-docs/swagger-config

server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka
